# -*- coding: utf-8 -*-
"""
Created on Sat Sep 28 20:22:59 2024

@author: hbozc
"""

services:
  - type: web
    name: rl-egfr-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    startCommand: streamlit run egfr_rl_app.py
